Layout/LineLength:
  Max: 200
  AutoCorrect: true

# Metrics/LineLength:
#   Max: 200
#   AutoCorrect: true  

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 140
  Exclude:
  - '**/*_spec.rb'

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/GuardClause:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**
    - node_modules/**/*
    - config/initializers/rswag-ui.rb
    - config/initializers/session_store.rb