version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  sidekiq:
    build: .
    image: cardeons-backend
    environment:
      SERVICE: sidekiq
      REDIS_URL: redis://redis/1
      DATABASE_URL: postgres://postgres:password@db/cardeons-production
      RAILS_ENV: production
      SECRET_KEY_BASE: test
      ENC_KEY: test
      DEV_TOOL_ENABLED: enabled
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
  redis:
    image: redis
  web:
    build: .
    image: cardeons-backend
    command: bundle exec rails server -b 0.0.0.0
    environment:
      SERVICE: web
      REDIS_URL: redis://redis/1
      DATABASE_URL: postgres://postgres:password@db/cardeons-production
      RAILS_ENV: production
      SECRET_KEY_BASE: test
      ENC_KEY: test
      DEV_TOOL_ENABLED: enabled
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
