 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/centercards", type: :request do
  # Centercard. As you add validations to Centercard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Centercard.create! valid_attributes
      get centercards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      centercard = Centercard.create! valid_attributes
      get centercard_url(centercard)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_centercard_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      centercard = Centercard.create! valid_attributes
      get edit_centercard_url(centercard)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Centercard" do
        expect {
          post centercards_url, params: { centercard: valid_attributes }
        }.to change(Centercard, :count).by(1)
      end

      it "redirects to the created centercard" do
        post centercards_url, params: { centercard: valid_attributes }
        expect(response).to redirect_to(centercard_url(Centercard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Centercard" do
        expect {
          post centercards_url, params: { centercard: invalid_attributes }
        }.to change(Centercard, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post centercards_url, params: { centercard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested centercard" do
        centercard = Centercard.create! valid_attributes
        patch centercard_url(centercard), params: { centercard: new_attributes }
        centercard.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the centercard" do
        centercard = Centercard.create! valid_attributes
        patch centercard_url(centercard), params: { centercard: new_attributes }
        centercard.reload
        expect(response).to redirect_to(centercard_url(centercard))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        centercard = Centercard.create! valid_attributes
        patch centercard_url(centercard), params: { centercard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested centercard" do
      centercard = Centercard.create! valid_attributes
      expect {
        delete centercard_url(centercard)
      }.to change(Centercard, :count).by(-1)
    end

    it "redirects to the centercards list" do
      centercard = Centercard.create! valid_attributes
      delete centercard_url(centercard)
      expect(response).to redirect_to(centercards_url)
    end
  end
end
