 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/graveyards", type: :request do
  # Graveyard. As you add validations to Graveyard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Graveyard.create! valid_attributes
      get graveyards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      graveyard = Graveyard.create! valid_attributes
      get graveyard_url(graveyard)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_graveyard_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      graveyard = Graveyard.create! valid_attributes
      get edit_graveyard_url(graveyard)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Graveyard" do
        expect {
          post graveyards_url, params: { graveyard: valid_attributes }
        }.to change(Graveyard, :count).by(1)
      end

      it "redirects to the created graveyard" do
        post graveyards_url, params: { graveyard: valid_attributes }
        expect(response).to redirect_to(graveyard_url(Graveyard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Graveyard" do
        expect {
          post graveyards_url, params: { graveyard: invalid_attributes }
        }.to change(Graveyard, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post graveyards_url, params: { graveyard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested graveyard" do
        graveyard = Graveyard.create! valid_attributes
        patch graveyard_url(graveyard), params: { graveyard: new_attributes }
        graveyard.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the graveyard" do
        graveyard = Graveyard.create! valid_attributes
        patch graveyard_url(graveyard), params: { graveyard: new_attributes }
        graveyard.reload
        expect(response).to redirect_to(graveyard_url(graveyard))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        graveyard = Graveyard.create! valid_attributes
        patch graveyard_url(graveyard), params: { graveyard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested graveyard" do
      graveyard = Graveyard.create! valid_attributes
      expect {
        delete graveyard_url(graveyard)
      }.to change(Graveyard, :count).by(-1)
    end

    it "redirects to the graveyards list" do
      graveyard = Graveyard.create! valid_attributes
      delete graveyard_url(graveyard)
      expect(response).to redirect_to(graveyards_url)
    end
  end
end
