---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users.json":
    get:
      summary: list all the users
      tags:
      - User
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                  required:
                  - id
                  - name
                  - email
  "/users/{id}.json":
    get:
      summary: show user
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
  "/registrations":
    post:
      summary: Creates a user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: password can't be blank, name can't exist, e-mail can't exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - name
              - email
              - password
  "/sessions":
    post:
      summary: Logs in a user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: user logged in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/cards.json":
    get:
      summary: list all the cards
      tags:
      - Cards
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        type:
                          type: string
                        description:
                          type: string
                        image:
                          type: string
                        action:
                          type: string
                        draw_chance:
                          type: string
                        level:
                          type: string
                        element:
                          type: string
                        bad_things:
                          type: string
                        rewards_treasure:
                          type: string
                        good_against:
                          type: string
                        bad_against:
                          type: string
                        good_against_value:
                          type: string
                        bad_against_value:
                          type: string
                        element_modifier:
                          type: string
                        atk_points:
                          type: string
                        item_category:
                          type: string
                        has_combination:
                          type: string
                        level_amount:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        url:
                          type: string
                      required:
                      - id
                      - type
                      - attributes
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://cardeons-develop.herokuapp.com/
