# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# name: Ruby

# on:
#   push:
#     branches: [  master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   test:

#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['3.0']


#     services:
#       db:
#         image: postgres:11
#         ports: ['5432:5432']
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5


#     steps:
#     - uses: actions/checkout@v1
#     - name: Set up Ruby 3.0
#       uses: actions/setup-ruby@v1
#       with:
#         ruby-version: 3.0
#     - name: Build and test with Rake
#       env:
#         PGHOST: 127.0.0.1
#         PGUSER: postgres
#         RAILS_ENV: test
#       run: |
#         sudo apt-get -yqq install libpq-dev
#         gem install bundler
#         bundle install --jobs 4 --retry 3
#         bundle exec rails db:create
#         bundle exec rails db:migrate
#         bundle exec rails test:system
        
    # - name: Connect to PostgreSQL
    #   # Runs a script that creates a PostgreSQL client, populates
    #   # the client with data, and retrieves data
    #   run: node client.js
    #   # Environment variable used by the `client.js` script to create a new PostgreSQL client.
    #   env:
    #     # The hostname used to communicate with the PostgreSQL service container
    #     POSTGRES_HOST: postgres
    #     # The default PostgreSQL port
    #     POSTGRES_PORT: 5432
    # - name: Run tests
    #   run: bundle exec rake
